train_batch_size: 6
valid_batch_size: 6
test_batch_size: 6
num_workers: 4
shuffle_flag: False
lr: 0.001 # (0.1 , 0.01 , 0.001 , 0.0001)
epochs: 2
warmup_steps: 0
gpu_flag: True
train: False
model_name : None #"model0"