workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-8
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/dtumlops-406109/train_gpu@sha256:c4529acd25939909ed701115a5174a5427087d16b995450a32552f294e7dfad5
# if you want the latest image, use this instead: imageUri: gcr.io/dtumlops-406109/train@sha256:latent or any tag that you have specified