#config.yaml

data_cleaning:
  test_valid_size : 0.2
  train_size : 0.5
  trim_num : 200
  image_width: 128
  image_height: 128

dirs:
  train_dir: ${hydra:runtime.cwd}/data/external/fruit_images/train
  valid_dir: ${hydra:runtime.cwd}/data/external/fruit_images/valid
  data_dir: ${hydra:runtime.cwd}/data/external/fruit_images
  external_dir: ${hydra:runtime.cwd}/data/external