# models_config.yaml
wandb:
  api_key: "a1582d7e00e1d4c88d9f547b9a755237ffa63871"
  project: "Project_MLOps"

defaults:
  - params: exp1

dirs:
  train_dir: ${hydra:runtime.cwd}/data/processed/train
  valid_dir: ${hydra:runtime.cwd}/data/processed/valid
  test_dir: ${hydra:runtime.cwd}/data/processed/test
  model_dir: ${hydra:runtime.cwd}/src/models/saved_models/
  
model_path: "google/vit-base-patch16-224-in21k"

gcs:
  bucket_name: "dtu_mlops_saved_models"
  blob_name: "saved_models"
  credentials_file: "${hydra:runtime.cwd}/dtumlops-406109-ac8fa5c6b516.json"
  saved_dir: "/src/models/saved_models/"